### ISSUE TITLE
Export `"LEVEL :"` HUD text as a translation

### ISSUE THREAD

**Issue by arkaht** [Guthen/guthscpkeycard#7]
Location in the [code](https://github.com/Guthen/guthscpkeycard/blob/update-to-guthscpbase-remaster/lua/guthscp/modules/guthscpkeycard/client.lua#L24).

**Comment by Guthen** [comment]
Fixed with [05741a3](https://github.com/Guthen/guthscpkeycard/commit/05741a32ac9e4feffbc487ec7ab1bb29fcb1ab16)
